server:
  port: 18083
  servlet:
    context-path: /userApi

mybatis:
  typeAliasesPackage: com.hw.example.pojo
  mapperLocations: classpath:mapper/*Mapper.xml

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/gongan?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    initialSize: 1
    minIdle: 3
    maxActive: 20
    maxWait: 60000
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 30000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
  redis:
    host: localhost
    password: root
    port: 6379
    database: 8
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
    timeout: 0
  server:
    compression:
      request:
        # 开启请求压缩
        enabled: true
        # 配置压缩支持的 MIME TYPE
        mime-types: text/xml,application/xml,application/json
        # 配置压缩数据大小的下限
        min-request-size: 2048
      response:
        # 开启响应压缩
        enabled: true
#  cloud:        # gateWay 以后用
#    gateway:
#      discovery:
#        locator:
#          enabled: true
#eureka:
#  client:
#    serviceUrl:
#      defaultZone: http://39.96.27.192:18082/eureka/

feign:
  sentinel:
    enabled: true
  httpclient:
    enabled: false
  okhttp:
    enabled: true

ribbon:
  ReadTimeout: 5
  ConnectTimeout: 5

apache:
  rocketmq:
    namesrvAddr: 192.168.135.73:9876
    producer:
      producerGroup: wxProducer
      topic: logTopic
