server:
  port: 18080
spring:
  application:
      name: wxin-GatewayService
  redis:
      host: 127.0.0.1
      port: 6379
      database: 1
  cloud:
    nacos:
      discovery:
        namespace: wxin
        server-addr: 39.96.27.192:8848
        username: nacos
        password: nacos
        cluster-name: ${spring.application.name}
    gateway:
      routes:
        - id: userService_route
          uri: lb://wxin-UserService
          predicates:
            - Path=/userCallIntegral/**
          filters:
            - name: RequestRateLimiter
              args:
                redis-rate-limiter:
                  replenishRate: 3 #令牌补充的频率，每次就一个
                  burstCapacity: 20 #令牌桶的最大容量,允许在一秒钟内完成的最大请求数
                key-resolver: "#{@ipKeyResolver}"
        - id: integralService_route
          uri: lb://wxin-IntegralService
          predicates:
            - Path=/integralService/**
    sentinel:
      # 取消控制台懒加载
      eager: true
      transport:
        # 控制台地址
        dashboard: 192.168.135.110:8718