server:
  port: 18082

eureka:
  instance:
    hostname: 39.96.27.192
    #每间隔5s，向服务端发送一次心跳
    lease-renewal-interval-in-seconds: 5
    #告诉服务端，如果我20s之内没有给你发心跳，就代表我“死”了，将我踢出掉。
    lease-expiration-duration-in-seconds: 20
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/
  server:
      # 测试时关闭自我保护机制，保证不可用服务及时踢出
      enable-self-preservation: false

